project_id = "alcvwvdjbjyfgqrudddi"

[functions.check-registration-status]
verify_jwt = false

[functions.sync-monthly-rent]
verify_jwt = false

[functions.auth-password-signin]
verify_jwt = false

[functions.auth-password-signup]
verify_jwt = false

[functions.auth-password-reset]
verify_jwt = false